name: termux-setup-full
on:
  workflow_dispatch:
jobs:
  install:
    timeout-minutes: 360
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Prepare
        timeout-minutes: 360
        run: |
          cd ~
          sudo apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install curl git perl -y
          source /etc/os-release
          curl --retry 100 --retry-connrefused --retry-delay 5 -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo tee /etc/apt/trusted.gpg.d/docker.asc >/dev/null
          echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $UBUNTU_CODENAME stable" | sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
          sudo apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install docker-ce -y
          git clone https://github.com/Willie169/termux-sh.git
          cd termux-sh
          perl -i -pe 's/^## CONFIG START/set -euxo pipefail/;
          s/^UBUNTUINSTALL=1/UBUNTUINSTALL=0/;
          s/uv sync/ANDROID_API_LEVEL=24 uv sync/' termux-setup.sh
      - name: Run termux-setup.sh
        timeout-minutes: 360
        run: |
          sudo docker run --rm -v "$HOME/termux-sh:/data/data/com.termux/files/home/termux-sh" -w "/data/data/com.termux/files/home/termux-sh" --privileged termux/termux-docker bash -c '
            set -euxo pipefail
            echo "deb https://packages.termux.dev/apt/termux-main stable main" > /data/data/com.termux/files/usr/etc/apt/sources.list
            ./termux-setup.sh
          '
