name: termux-setup
on:
  workflow_dispatch:
jobs:
  install:
    timeout-minutes: 360
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Prepare
        timeout-minutes: 360
        run: |
          cd ~
          git clone https://github.com/Willie169/termux-sh.git
      - name: Run termux-setup.sh
        timeout-minutes: 360
        run: |
          sudo docker run --rm -v "$HOME/termux-sh:/data/data/com.termux/files/home/termux-sh" -w "/data/data/com.termux/files/home/termux-sh" --privileged termux/termux-docker bash -c '
            set -euxo pipefail
            echo "deb https://packages.termux.dev/apt/termux-main stable main" > /data/data/com.termux/files/usr/etc/apt/sources.list
            ./termux-setup.sh --test
          '
