name: termux-setup-test

on:
  workflow_dispatch:

jobs:
  working:
    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04
            architecture: i686
          - runner: ubuntu-24.04
            architecture: x86_64
          - runner: ubuntu-24.04-arm
            architecture: arm
          - runner: ubuntu-24.04-arm
            architecture: aarch64
    runs-on: ${{ matrix.runner }}
    container:
      image: termux/termux-docker:${{ matrix.architecture }}
      volumes: 
        - /tmp/node20:/__e/node20
    env:
      TERMUX_MAIN_PACKAGE_FORMAT: debian
      ANDROID_ROOT: /system
      ANDROID_DATA: /data
      PREFIX: /data/data/com.termux/files/usr
      HOME: /data/data/com.termux/files/home
      PATH: /data/data/com.termux/files/usr/bin
      TMPDIR: /data/data/com.termux/files/usr/tmp
      LANG: en_US.UTF-8
      TZ: UTC
    steps:
      - name: Prepare
        run: |
          ln -sf ${PREFIX}/etc/termux/mirrors/default ${PREFIX}/etc/termux/chosen_mirrors
          /entrypoint.sh pkg upgrade -y
          chmod -R o+x ${PREFIX}/bin
          /entrypoint.sh pkg install nodejs-lts -y
          ln -sf ${PREFIX}/bin /__e/node20/bin
      - name: Setup
        run: |
          /entrypoint.sh pkg install git -y
          cd ~ && git clone https://github.com/Willie169/termux-sh.git
      - name: Patch script
        run: |
          cd ~/termux-sh
          sed -Ei 's/DEBIANINSTALL=0/DEBIANINSTALL=1/; s/^(pkg|pip|npm|proot-distro)/\/entrypoint.sh \1/; s/\&\& (pkg|pip|npm|proot-distro)/\&\& \/entrypoint.sh \1/; s/\|\| (pkg|pip|npm|proot-distro)/|| \/entrypoint.sh \1/; s/pkg install ($PKG|xfce4) -y/pkg install \1 -y --dry-run/' termux-setup.sh
          cd ~
      - name: Main
        run: |
          cd ~
          bash ~/termux-sh/termux-setup.sh > termux-setup.log
      - name: Upload log file
      - uses: actions/upload-artifact@v4.6.0
        with:
          name: termux-setup-${{ matrix.architecture }}.log
          path: termux-setup.log
