name: termux-setup
on:
  workflow_dispatch:
jobs:
  install:
    timeout-minutes: 360
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Prepare
        timeout-minutes: 360
        run: |
          cd ~
          sudo apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install curl -y
          source /etc/os-release
          curl --retry 100 --retry-connrefused --retry-delay 5 -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo tee /etc/apt/trusted.gpg.d/docker.asc >/dev/null
          echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $UBUNTU_CODENAME stable" | sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
          sudo apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install docker-ce -y
      - name: Run termux-setup.sh
        timeout-minutes: 360
        run: |
          sudo docker run --rm --privileged termux/termux-docker bash -c '
            set -euxo pipefail
            echo "deb https://packages.termux.dev/apt/termux-main stable main" > /data/data/com.termux/files/usr/etc/apt/sources.list
            apt update
            apt upgrade -y
            apt install x11-repo tur-repo -y
            apt install perl -y
          '
