name: ubuntu-debian
on:
  workflow_dispatch:
jobs:
  ubuntu-debian:
    timeout-minutes: 360
    strategy:
      matrix:
        runner:
          - ubuntu-24.04-arm
        image:
          - ubuntu:24.04
          - ubuntu:26.04
          - debian:13
    runs-on: ${{ matrix.runner }}
    container:
      image: ${{ matrix.image }}
    steps:
      - name: Checkout repository
        timeout-minutes: 360
        uses: actions/checkout@v4
      - name: Run ubuntu-debian.sh
        timeout-minutes: 360
        run: ./ubuntu-debian.sh --test
